### ISSUE TITLE
Third party JS files

### ISSUE THREAD

**Issue by irsdl** [h3xstream/burp-retire-js#21]
Is this possible to raise an issue when third party outdated JS files are used in a website?
At the moment issues are only listed in those third party sites which is not ideal.

**Comment by h3xstream** [comment]
Please give an example for each.. it should be finding both.

**Comment by irsdl** [comment]
I have a site that uses several external JS file such as:
`<script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>`
I know retire.js normally picks this up if hosted locally, but it hasn't in this case.

**Comment by h3xstream** [comment]
I created a test page with the `googleapis.com` script and it trigger the expected behavior:

![Issue RetireJs](https://user-images.githubusercontent.com/593130/28122862-6e84a62e-66ed-11e7-8346-7361be65e045.png)

Two cause:
 - Look at issues from googleapis.com
 - Maybe the page was cached by the browser (`jquery.min.js`) and therefor the proxy does not see the request.

**Comment by irsdl** [comment]
I think you misunderstood me. I meant I would like to see this issue, to be listed under "target.com" that contains this HTML tag. 

The reason is that the target application is big and you cannot cross-reference everything with all those external domains it has used.

So in this example, this affected jquery file actually can make the "target.com" vulnerable so I think it should be reported in "target.com" as well as "ajax.googleapis.com". So then the "target.com" website should use a more secure jquery library perhaps.

**Comment by h3xstream** [comment]
Ok I understand the feature request now.

Thinking about it .. I am pretty sure it is a catch 22 situation for the tester point of view.

 - Since only URI heuristic can be used to identify external scripts in HTML page, some additional logic would be need to **track where resource are loaded** to get the complete coverage of rules.
 - Some server configuration will **disable referer header** or make dynamic script loading, in those case, it will not be possible to mark script at the source.

The danger I see for user seeing `<script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>` marked in the HTML page is that they will expected it to always find the issue on the hosting page...

# Proposition

 - Find external script **ONLY based on URI property** from RetireJs.
 - Add a warning to the description "Important: The issue are not always reported at the source. (HTML page) To have a complete coverage, you need to review CDN sites from the site map."
 - The script file will also be mark with an issue

This is not a final statement. I am still thinking about it. 😄

**Comment by h3xstream** [comment]
It will look like this :
![preview_external_script](https://user-images.githubusercontent.com/593130/29288946-bb87135a-8108-11e7-8b74-c8c9351b0ebc.png)
Let me know if you think it's complete.
