### ISSUE TITLE
Generated alert names

### ISSUE THREAD

**Issue by rvolgers** [h3xstream/burp-retire-js#30]
The plugin currently generates alert titles that include the filename and the name of the library. That doesn't match what the native detections of ZAP/Burp do (as far as I can tell). 

In ZAP at least (and in Burp as well I think?) issues usually have a generic name without dynamic content so multiple issues of the same type will be grouped together in the GUI, and you can expand it if you want to see all the separate details. Since RetireJS puts the filename and library name in the issue name, issues will not be grouped together and for some sites it can result in a large amount of RetireJS issues in the UI compared to other types of issues. 

I can submit a patch to use a generic issue name (something like "Outdated and vulnerable JavaScript libraries found" seems good), but wanted to ask first if you agree with this change.

**Comment by amroot** [comment]
First, great plugin! 

Regarding "and in Burp as well I think", I can confirm it is the same. 

One finding per library rather than page would be great. :)

**Comment by h3xstream** [comment]
@rvolgers I have a small objection.
If you are scanning a large website, you will get multiple versions of the same libraries that can be identified and many libraries found. Regrouping the vulnerabilities in small groups helps the navigation. Consider that you have 100 outdated Javascript libraries. Having a single list will not be the most efficient option to do triage.

Regrouping per vulnerability types (CVE X for JQuery X) would make sense for security analyst.
From a developer perspective, regrouping per file (X.js has vulnerabilities) is logical because often transitive dependencies are bundled together with modern dependencies management. Updating the higher level version will fix the transitive ones.

@rvolgers If you want to do it, you can test it. It should be a small change overall. Test it on big website and the sandbox (`/test-samples/` directory). If it is able to report different vulnerabilities on the same file with different vulnerabilities than it's ok.

**Comment by rvolgers** [comment]
@h3xstream I agree with your concerns that grouping too much will hurt navigability, except that they apply equally to many other issue types. So I'm going to err on the side of consistency for now I think. 

I have implemented my original idea (grouping all RetireJS issues) using ZAP's alert override functionality for now (it allows overriding alert titles by plugin id). We are still in early stages of evaluating this tooling anyway so will be some time before I get feedback on this. 

Also I noticed your plugin has a different license than ZAP and RetireJS, were you still planning to change that? Otherwise we might move to another solution anyway, such as Google's Lighthouse plugin also detects outdated JS. There is just not a lot of appetite for getting another license involved in this.

**Comment by jourzero** [comment]
I was going to report that inconsistency (using "The file <PATH> includes a vulnerable version of...") with other Burp findings myself here until I saw this issue. I agree with @rvolgers on this one. I love this extension and I'd hate having to fork/build my own due to a misunderstanding. IMO, we shouldn't be building extensions with issue names that contain different instances of the same issue.  Just my 2 cents (+1 for @rvolgers for this issue and +1 for @h3xstream for this awesome extension).

**Comment by h3xstream** [comment]
@rvolgers @jourzero I will look at this eventually. Their is some test to do 

@rvolgers Are you referring to https://github.com/h3xstream/burp-retire-js/blob/eddb50d2931351929fc7f57f458cf5d8990313ef/retirejs-burp-plugin/src/main/java/burp/BurpExtender.java#L36 for the license. This is a mistake. This project should be considered Apache 3.0 (same as Retire.Js core).

**Comment by rvolgers** [comment]
@h3xstream 

I had noted the potential license issue somewhere between my first and second post here, but didn't  post about it since an issue was already filed about it. Apparently the license was changed to Apache 2.0 in the readme and LICENSE file before I made the second post on February 12th and I didn't notice! That's great, and thanks for pointing it out.

I believe @jourzero is just referring to the same thing I pointed out, that most Burp plugins (and ZAP plugins) take the approach of having a single static issue name with no dynamic content. This plugin does something different, i.e. it is inconsistent with the behavior of other plugins and built-in detections.

**Comment by jourzero** [comment]
@h3xstream, what @rvolgers said is what I meant. Burp issues have static names and the retire.js plugin has a dynamic name (containing the file name). The result is a much longer issue list. I hope this helps clarify. Thanks again for the great plugin. Very useful.

**Comment by MarioVilas** [comment]
Dynamic names aren't so much the problem, they can be helpful. But I think what we all want here is something like having the name and version of the library found in the issue title... but NOT the URL where it was found.

The typical scenario where the current behavior breaks is when you have a web application with an old version of jQuery embedded into every page. Suddenly you're drowning in duplicated issues and the Burp GUI cannot coalesce them, because having different titles mean having entirely different issues.

**Comment by h3xstream** [comment]
>  " old version of jQuery embedded into every page."

Ok Now I understand. I don't know when I'll have the time to do this small change.

**Comment by h3xstream** [comment]
Add the moment I only tested the change made by Mario which covers Burp only.

I will do the update for ZAP later.
